export const accounting = [
  {
    key: "chartOfAccounts",
    name: "Accounts",
    schema: "/accounting-api#/schemas/Account",
    product: "accounting",
    description: "",
  },
  {
    key: "accountTransactions",
    name: "Account transactions",
    schema: "/accounting-api#/schemas/AccountTransaction",
    product: "accounting",
    description: "",
  },
  {
    key: "balanceSheet",
    name: "Balance sheet",
    schema: "/accounting-api#/schemas/BalanceSheet",
    product: "accounting",
    description: "",
  },
  {
    key: "bankAccounts",
    name: "Bank accounts",
    schema: "/accounting-api#/schemas/BankAccount",
    product: "accounting",
    description: "",
  },
  {
    key: "bankTransactions",
    name: "Bank transactions",
    schema: "/accounting-api#/schemas/BankTransactions",
    product: "accounting",
    description: "",
  },
  {
    key: "bills",
    name: "Bills",
    schema: "/accounting-api#/schemas/Bill",
    product: "accounting",
    description: "",
  },
  {
    key: "billCreditNotes",
    name: "Bill credit notes",
    schema: "/accounting-api#/schemas/BillCreditNote",
    product: "accounting",
    description: "",
  },
  {
    key: "billPayments",
    name: "Bill payments",
    schema: "/accounting-api#/schemas/BillPayment",
    product: "accounting",
    description: "",
  },
  {
    key: "cashFlowStatement",
    name: "Cash flow statement",
    schema: "/accounting-api#/schemas/CashFlowStatement",
    product: "accounting",
    description: "",
  },
  {
    key: "company",
    name: "Company info",
    schema: "/accounting-api#/schemas/CompanyDataset",
    product: "accounting",
    description: "",
  },
  {
    key: "creditNotes",
    name: "Credit notes",
    schema: "/accounting-api#/schemas/CreditNote",
    product: "accounting",
    description: "",
  },
  {
    key: "customers",
    name: "Customers",
    schema: "/accounting-api#/schemas/Customer",
    product: "accounting",
    description: "",
  },
  {
    key: "directCosts",
    name: "Direct costs",
    schema: "/accounting-api#/schemas/DirectCost",
    product: "accounting",
    description: "",
  },
  {
    key: "directIncomes",
    name: "Direct incomes",
    schema: "/accounting-api#/schemas/DirectIncome",
    product: "accounting",
    description: "",
  },
  {
    key: "invoices",
    name: "Invoices",
    schema: "/accounting-api#/schemas/Invoice",
    product: "accounting",
    description: "",
  },
  {
    key: "items",
    name: "Items",
    schema: "/accounting-api#/schemas/Item",
    product: "accounting",
    description: "",
  },
  {
    key: "journals",
    name: "Journals",
    schema: "/accounting-api#/schemas/Journal",
    product: "accounting",
    description: "",
  },
  {
    key: "journalEntries",
    name: "Journal entries",
    schema: "/accounting-api#/schemas/JournalEntry",
    product: "accounting",
    description: "",
  },
  {
    key: "payments",
    name: "Payments",
    schema: "/accounting-api#/schemas/Payment",
    product: "accounting",
    description: "",
  },
  {
    key: "paymentMethods",
    name: "Payment methods",
    schema: "/accounting-api#/schemas/PaymentMethod",
    product: "accounting",
    description: "",
  },
  {
    key: "profitAndLoss",
    name: "Profit and loss",
    schema: "/accounting-api#/schemas/ProfitAndLossReport",
    product: "accounting",
    description: "",
  },
  {
    key: "purchaseOrders",
    name: "Purchase orders",
    schema: "/accounting-api#/schemas/PurchaseOrder",
    product: "accounting",
    description: "",
  },
  {
    key: "salesOrders",
    name: "Sales orders",
    schema: "/accounting-api#/schemas/SalesOrder",
    product: "accounting",
    description: "",
  },
  {
    key: "suppliers",
    name: "Suppliers",
    schema: "/accounting-api#/schemas/Supplier",
    product: "accounting",
    description: "",
  },
  {
    key: "taxRates",
    name: "Tax rates",
    schema: "/accounting-api#/schemas/TaxRate",
    product: "accounting",
    description: "",
  },
  {
    key: "trackingCategories",
    name: "Tracking categories",
    schema: "/accounting-api#/schemas/TrackingCategory",
    product: "accounting",
    description: "",
  },
  {
    key: "transfers",
    name: "Transfers",
    schema: "/accounting-api#/schemas/Transfer",
    product: "accounting",
    description: "",
  },
]

export const banking = [
  {
    key: "banking-accounts",
    name: "Accounts",
    schema: "/banking-api#/schemas/Account",
    product: "banking",
    description: "The SMB's bank accounts, with rich data like balances, account numbers and institutions holding the accounts.",
  },
  {
    key: "banking-accountBalances",
    name: "Account balances",
    schema: "/banking-api#/schemas/AccountBalance",
    product: "banking",
    description: "Balances for a bank account including end-of-day batch balance or running balances per transaction.",
  },
  {
    key: "banking-transactions",
    name: "Transactions",
    schema: "/banking-api#/schemas/Transaction",
    product: "banking",
    description: "Transactions incurred by the bank account.",
  },
  {
    key: "banking-transactionCategories",
    name: "Transaction categories",
    schema: "/banking-api#/schemas/TransactionCategory",
    product: "banking",
    description: "Hierarchical categories associated with a transaction for greater contextual meaning to transaction activity.",
  },
]

export const commerce = [
  {
    key: "commerce-companyInfo",
    name: "Company info",
    schema: "/commerce-api#/schemas/CompanyInfo",
    product: "commerce",
    description: "Details of a company, such as their address, phone number, and company registration.",
  },
  {
    key: "commerce-customers",
    name: "Customers",
    schema: "/commerce-api#/schemas/Customer",
    product: "commerce",
    description: "Customers who have placed orders with the company.",
  },
  {
    key: "commerce-disputes",
    name: "Disputes",
    schema: "/commerce-api#/schemas/Dispute",
    product: "commerce",
    description: "Transactions that customers have challenged.",
  },
  {
    key: "commerce-locations",
    name: "Locations",
    schema: "/commerce-api#/schemas/Locations",
    product: "commerce",
    description: "Geographic locations where product variant inventory is held.",
  },
  {
    key: "commerce-orders",
    name: "Orders",
    schema: "/commerce-api#/schemas/Order",
    product: "commerce",
    description: "Orders received by a company, including payments, service charges, and refunds.",
  },
  {
    key: "commerce-payments",
    name: "Payments",
    schema: "/commerce-api#/schemas/Payment",
    product: "commerce",
    description: "Amounts reserved against the customer's funding source.",
  },
  {
    key: "commerce-paymentMethods",
    name: "Payment methods",
    schema: "/commerce-api#/schemas/PaymentMethod",
    product: "commerce",
    description: "Represents the payment methods used by customers to make payments.",
  },
  {
    key: "commerce-products",
    name: "Products",
    schema: "/commerce-api#/schemas/Product",
    product: "commerce",
    description: "Products a company has available on the system, including the price and quantity of those products, and product variants.",
  },
  {
    key: "commerce-productCategories",
    name: "Product categories",
    schema: "/commerce-api#/schemas/ProductCategory",
    product: "commerce",
    description: "Categories of products.",
  },
  {
    key: "commerce-taxComponents",
    name: "Tax components",
    schema: "/commerce-api#/schemas/TaxComponent",
    product: "commerce",
    description: "Tax components",
  },
  {
    key: "commerce-transactions",
    name: "Transactions",
    schema: "/commerce-api#/schemas/Transaction",
    product: "commerce",
    description: "Financial transactions recorded in the system.",
  },
]

export const bankfeeds = [
  {
    key: "bankfeedsbankaccount",
    name: "Bank account",
    schema: "/bank-feeds-api#/schemas/BankFeedBankAccount",
    product: "bank-feeds",
    description: "",
  },
]

export const dataTypes = [
  ...accounting,
  ...banking,
  ...commerce,
  ...bankfeeds,
]