name: OAS Changelog Generator

on:
  schedule:
    # Run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml gitpython

      - name: Generate changelog
        id: changelog
        env:
          GITHUB_OUTPUT: ${{ github.workspace }}/output.txt
        run: |
          python .github/scripts/generate_oas_changelog.py
          if [ -f output.txt ]; then
            cat output.txt >> $GITHUB_OUTPUT
          fi

      - name: Set date variables
        id: date
        run: |
          echo "date=$(date +%Y-%m)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changelog.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: Add OAS changelog for ${{ steps.date.outputs.date }}"
          title: "docs: OAS Changelog for ${{ steps.date.outputs.date }}"
          body: |
            This PR contains the OAS changelog for the current month.
            
            Changes were detected in the OAS repository and have been summarized in a new blog post.
          branch: "oas-changelog-${{ steps.date.outputs.date }}"
          base: main
          delete-branch: true
          labels: |
            documentation
            automated pr 