name: OAS sitemap builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Execute script and save output
        run: |
          node script.js > static/oas/sitemap.xml

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update output.xml" || echo "No changes to commit"
          git push
